import type { Metadata } from "next";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {StyledRoot} from "../theme/StyleRoot";
import Providers from "../store/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <StyledRoot>{children}</StyledRoot>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
